import type { IncomeEntry } from '@/types/api';
import { MOCK_INCOME_CATEGORIES } from './mock-categories';

export const MOCK_INCOMES: IncomeEntry[] = [
  {
    id:             'inc_101',
    ref:            'INC-101',
    date:           '2026-04-26',
    amount_minor:   85_000,
    tax_minor:      0,
    total_minor:    85_000,
    currency:       'MYR',
    category:       MOCK_INCOME_CATEGORIES[0],
    payment_option: 'bank',
    contact:        null,
    description:    'MBB current acct interest · Apr',
    internal_remark:null,
    reconciled:     false,
    share_url:      'https://scount.my/in/abc-101',
  },
  {
    id:             'inc_102',
    ref:            'INC-102',
    date:           '2026-04-22',
    amount_minor:   24_000,
    tax_minor:      0,
    total_minor:    24_000,
    currency:       'MYR',
    category:       MOCK_INCOME_CATEGORIES[1],
    payment_option: 'online',
    contact:        { id: 's_pos_partners', name: 'POS Partners', email: 'ar@pospartners.example' },
    description:    'Software licence rebate',
    internal_remark:'One-off — credit memo',
    reconciled:     true,
    share_url:      'https://scount.my/in/abc-102',
  },
  {
    id:             'inc_103',
    ref:            'INC-103',
    date:           '2026-04-12',
    amount_minor:   500_000,
    tax_minor:      0,
    total_minor:    500_000,
    currency:       'MYR',
    category:       MOCK_INCOME_CATEGORIES[3],
    payment_option: 'bank',
    contact:        null,
    description:    'MDEC digitalisation grant — Phase 1',
    internal_remark:'Tracked separately for audit',
    reconciled:     false,
    share_url:      'https://scount.my/in/abc-103',
  },
];
