import type { Quotation } from '@/types/api';

/**
 * Hand-authored fixtures matching mockups/quotation.html so the screens
 * render something believable before the backend is up. Will be
 * replaced by `useQuotationList()` / `useQuotation(id)` against
 * /v1/quotations once the Sanctum auth + axios client land.
 *
 * Tax is applied at the document level (SST 6%). line_total_minor is
 * the line subtotal (qty × unit_price), tax_minor sits on the document.
 */
export const MOCK_QUOTATIONS: Quotation[] = [
  {
    id:           'qt_038',
    ref:          'QT-038',
    status:       'open',
    issue_date:   '2026-04-25',
    expires_at:   '2026-05-25',
    contact_name: 'CityWorks Sdn Bhd',
    contact:      { id: 'c_city', name: 'CityWorks Sdn Bhd', email: 'accounts@cityworks.example' },
    delivery_days:        30,
    currency:             'MYR',
    subtotal_minor:       820_000,
    tax_minor:            49_200,
    total_minor:          869_200,
    line_items: [
      { name: 'Site survey',     description: 'Q2 portfolio · 4 properties', quantity: 1, unit_price_minor: 500_000, tax_code: 'SST6', line_total_minor: 500_000 },
      { name: 'Drafting hours',  description: null,                           quantity: 8, unit_price_minor:  40_000, tax_code: 'SST6', line_total_minor: 320_000 },
    ],
    terms_and_conditions: 'Net 30 from acceptance. 50% deposit on signing.',
    remarks:              'Please confirm by 30 Apr.',
    internal_remarks:     null,
    linked_invoice:       null,
    share_url:            'https://scount.my/q/abc-038',
  },
  {
    id:           'qt_037',
    ref:          'QT-037',
    status:       'open',
    issue_date:   '2026-04-22',
    expires_at:   '2026-05-22',
    contact_name: 'Borneo Coffee Co.',
    contact:      { id: 'c_borneo', name: 'Borneo Coffee Co.', email: 'finance@borneo.example' },
    delivery_days:        30,
    currency:             'MYR',
    subtotal_minor:       2_320_000,
    tax_minor:            139_200,
    total_minor:          2_459_200,
    line_items: [
      { name: 'Audit retainer',       description: 'Quarterly audit · Q2',          quantity: 1, unit_price_minor: 1_800_000, tax_code: 'SST6', line_total_minor: 1_800_000 },
      { name: 'Compliance workshop',  description: '4 sessions × 90 min, recorded', quantity: 4, unit_price_minor:    130_000, tax_code: 'SST6', line_total_minor:   520_000 },
    ],
    terms_and_conditions: 'Net 30 from acceptance.',
    remarks:              null,
    internal_remarks:     'New logo — quote priced 5% under list to win the relationship.',
    linked_invoice:       null,
    share_url:            'https://scount.my/q/abc-037',
  },
  {
    id:           'qt_036',
    ref:          'QT-036',
    status:       'accepted',
    issue_date:   '2026-04-22',
    expires_at:   '2026-05-22',
    contact_name: 'PT Anugerah',
    contact:      { id: 'c_anugerah', name: 'PT Anugerah Sdn Bhd', email: 'billing@anugerah.example' },
    delivery_days:        30,
    currency:             'MYR',
    subtotal_minor:       1_180_000,
    tax_minor:            70_800,
    total_minor:          1_250_800,
    line_items: [
      { name: 'Audit retainer',      description: 'April retainer · scope per SOW', quantity: 1, unit_price_minor: 800_000, tax_code: 'SST6', line_total_minor: 800_000 },
      { name: 'Onboarding workshop', description: '4 sessions × 90 min',            quantity: 4, unit_price_minor:  50_000, tax_code: 'SST6', line_total_minor: 200_000 },
      { name: 'Setup fee',           description: 'One-time engagement setup',      quantity: 1, unit_price_minor: 180_000, tax_code: 'SST6', line_total_minor: 180_000 },
    ],
    terms_and_conditions: 'Net 30 from acceptance. 50% non-refundable deposit upon signing.',
    remarks:              'Please confirm by 30 Apr.',
    internal_remarks:     'Margin 40% — repeat client.',
    linked_invoice:       null,
    share_url:            'https://scount.my/q/abc-036',
  },
  {
    id:           'qt_034',
    ref:          'QT-034',
    status:       'declined',
    issue_date:   '2026-04-12',
    expires_at:   '2026-05-12',
    contact_name: 'Pesisir Marine',
    contact:      { id: 'c_pesisir', name: 'Pesisir Marine Sdn Bhd', email: 'ap@pesisir.example' },
    delivery_days:        45,
    currency:             'MYR',
    subtotal_minor:       641_509,
    tax_minor:            38_491,
    total_minor:          680_000,
    line_items: [
      { name: 'Marine equipment audit', description: 'Annual ISM audit pack', quantity: 1, unit_price_minor: 641_509, tax_code: 'SST6', line_total_minor: 641_509 },
    ],
    terms_and_conditions: 'Net 45.',
    remarks:              null,
    internal_remarks:     'Lost on price — competitor came in 18% lower.',
    linked_invoice:       null,
    share_url:            'https://scount.my/q/abc-034',
  },
  {
    id:           'qt_031',
    ref:          'QT-031',
    status:       'expired',
    issue_date:   '2026-03-15',
    expires_at:   '2026-04-15',
    contact_name: 'Acme Sdn Bhd',
    contact:      { id: 'c_acme', name: 'Acme Sdn Bhd', email: 'finance@acme.example' },
    delivery_days:        30,
    currency:             'MYR',
    subtotal_minor:       490_566,
    tax_minor:            29_434,
    total_minor:          520_000,
    line_items: [
      { name: 'Setup retainer', description: null, quantity: 1, unit_price_minor: 490_566, tax_code: 'SST6', line_total_minor: 490_566 },
    ],
    terms_and_conditions: 'Net 30.',
    remarks:              null,
    internal_remarks:     null,
    linked_invoice:       null,
    share_url:            'https://scount.my/q/abc-031',
  },
];
