import type { Contact } from '@/types/api';

export const MOCK_CONTACTS: Contact[] = [
  {
    id:               'c_anugerah',
    type:             'client',
    code:             'CL001',
    name:             'PT Anugerah Sdn Bhd',
    registration_no:  '202101000123',
    tax_id:           'SST-A12-345-67',
    email:            'billing@anugerah.example',
    phone:            '+60 12 345 6789',
    address_line1:    'Lot 5, Jalan Kuching',
    address_city:     'Kuching',
    address_state:    'Sarawak',
    address_postcode: '93000',
    address_country:  'Malaysia',
    outstanding_minor: 1_240_000,
    invoice_count:     3,
    quote_count:       1,
    currency:          'MYR',
    notes:             'Quarterly retainer client.',
    persons: [
      { id: 'p_anu_1', name: 'Sarah Wong', email: 'sarah@anugerah.example',  phone: '+60 12 111 2233' },
      { id: 'p_anu_2', name: 'Daniel Tan', email: 'daniel@anugerah.example', phone: null },
    ],
  },
  {
    id:               'c_borneo',
    type:             'client',
    code:             'CL002',
    name:             'Borneo Coffee Co.',
    registration_no:  '202203456789',
    tax_id:           null,
    email:            'finance@borneo.example',
    phone:            '+60 82 233 4455',
    address_line1:    '8 Jalan Padungan',
    address_city:     'Kuching',
    address_state:    'Sarawak',
    address_postcode: '93100',
    address_country:  'Malaysia',
    outstanding_minor: 620_000,
    invoice_count:     2,
    quote_count:       1,
    currency:          'MYR',
    notes:             null,
    persons: [
      { id: 'p_brn_1', name: 'Lim Mei Ling', email: 'meiling@borneo.example', phone: '+60 16 444 5566' },
    ],
  },
  {
    id:               'c_city',
    type:             'client',
    code:             'CL003',
    name:             'CityWorks Sdn Bhd',
    registration_no:  null,
    tax_id:           null,
    email:            'accounts@cityworks.example',
    phone:            '+60 03 7788 9900',
    address_line1:    null,
    address_city:     null,
    address_state:    null,
    address_postcode: null,
    address_country:  'Malaysia',
    outstanding_minor: 0,
    invoice_count:     0,
    quote_count:       2,
    currency:          'MYR',
    notes:             null,
    persons: [
      { id: 'p_city_1', name: 'Aiman Hakim', email: 'aiman@cityworks.example', phone: null },
      { id: 'p_city_2', name: 'Priya Devi',  email: 'priya@cityworks.example', phone: '+60 19 222 3344' },
      { id: 'p_city_3', name: 'Ravi Kumar',  email: null,                       phone: '+60 12 555 7788' },
    ],
  },
  {
    id:               'c_acme',
    type:             'client',
    code:             'CL004',
    name:             'Acme Sdn Bhd',
    registration_no:  null,
    tax_id:           null,
    email:            'finance@acme.example',
    phone:            null,
    address_line1:    null,
    address_city:     null,
    address_state:    null,
    address_postcode: null,
    address_country:  'Malaysia',
    outstanding_minor: 0,
    invoice_count:     1,
    quote_count:       0,
    currency:          'MYR',
    notes:             'All paid up.',
    persons: [],
  },
  {
    id:               's_tomei',
    type:             'supplier',
    code:             'SP001',
    name:             'Tomei Hardware',
    registration_no:  '199801056789',
    tax_id:           null,
    email:            'sales@tomei.example',
    phone:            '+60 03 2222 3333',
    address_line1:    null,
    address_city:     'Petaling Jaya',
    address_state:    'Selangor',
    address_postcode: '47800',
    address_country:  'Malaysia',
    outstanding_minor: 0,
    invoice_count:     0,
    quote_count:       0,
    currency:          'MYR',
    notes:             null,
    persons: [
      { id: 'p_tom_1', name: 'Eric Chai', email: 'eric@tomei.example', phone: null },
    ],
  },
  {
    id:               's_pos_partners',
    type:             'supplier',
    code:             'SP002',
    name:             'POS Partners',
    registration_no:  null,
    tax_id:           null,
    email:            'ar@pospartners.example',
    phone:            null,
    address_line1:    null,
    address_city:     null,
    address_state:    null,
    address_postcode: null,
    address_country:  'Malaysia',
    outstanding_minor: 0,
    invoice_count:     0,
    quote_count:       0,
    currency:          'MYR',
    notes:             null,
    persons: [],
  },
];
