import type { Invoice } from '@/types/api';

export const MOCK_INVOICES: Invoice[] = [
  {
    id:           'inv_478',
    ref:          'INV-478',
    status:       'overdue',
    issue_date:   '2026-03-23',
    due_date:     '2026-04-23',
    contact_name: 'Borneo Coffee Co.',
    contact:      { id: 'c_borneo', name: 'Borneo Coffee Co.', email: 'finance@borneo.example' },
    delivery_days:        30,
    currency:             'MYR',
    subtotal_minor:       584_906,
    tax_minor:            35_094,
    total_minor:          620_000,
    paid_minor:           0,
    line_items: [
      { description: 'Equipment maintenance · Q1', quantity: 1, unit_price_minor: 584_906, tax_code: 'SST6', line_total_minor: 620_000 },
    ],
    payments:             [],
    terms_and_conditions: 'Net 30. 1.5% per month on overdue balances.',
    remarks:              'Bank-in to MBB 5142-***-***. Email POP after.',
    internal_remarks:     'Slow payer — call before reminder.',
    recurrence: {
      enabled:    true,
      frequency:  'monthly',
      anchor_day: 23,
      next_at:    '2026-05-23',
      ends_at:    null,
      upcoming_cycles: [
        { issue_date: '2026-05-23', amount_minor: 620_000, currency: 'MYR' },
        { issue_date: '2026-06-23', amount_minor: 620_000, currency: 'MYR' },
        { issue_date: '2026-07-23', amount_minor: 620_000, currency: 'MYR' },
      ],
    },
    from_quotation:       { id: 'qt_031', ref: 'QT-031' },
    share_url:            'https://scount.my/i/abc-478',
  },
  {
    id:           'inv_481',
    ref:          'INV-481',
    status:       'sent',
    issue_date:   '2026-04-19',
    due_date:     '2026-05-19',
    contact_name: 'CityWorks Sdn Bhd',
    contact:      { id: 'c_city', name: 'CityWorks Sdn Bhd', email: 'accounts@cityworks.example' },
    delivery_days:        30,
    currency:             'MYR',
    subtotal_minor:       822_641,
    tax_minor:            49_359,
    total_minor:          872_000,
    paid_minor:           0,
    line_items: [
      { description: 'Site survey',          quantity: 1, unit_price_minor: 500_000, tax_code: 'SST6', line_total_minor: 530_000 },
      { description: 'Drafting hours',       quantity: 8, unit_price_minor:  40_000, tax_code: 'SST6', line_total_minor: 339_200 },
    ],
    payments:             [],
    terms_and_conditions: 'Net 30.',
    remarks:              null,
    internal_remarks:     null,
    recurrence:           null,
    from_quotation:       null,
    share_url:            'https://scount.my/i/abc-481',
  },
  {
    id:           'inv_482',
    ref:          'INV-482',
    status:       'paid',
    issue_date:   '2026-04-15',
    due_date:     '2026-04-30',
    contact_name: 'PT Anugerah',
    contact:      { id: 'c_anugerah', name: 'PT Anugerah Sdn Bhd', email: 'billing@anugerah.example' },
    delivery_days:        30,
    currency:             'MYR',
    subtotal_minor:       1_169_811,
    tax_minor:            70_189,
    total_minor:          1_240_000,
    paid_minor:           1_240_000,
    line_items: [
      { description: 'Audit retainer · April',  quantity: 1, unit_price_minor: 800_000, tax_code: 'SST6', line_total_minor: 848_000 },
      { description: 'Onboarding workshop',     quantity: 4, unit_price_minor:  50_000, tax_code: null,   line_total_minor: 200_000 },
      { description: 'Setup fee',               quantity: 1, unit_price_minor: 180_000, tax_code: 'SST6', line_total_minor: 190_800 },
    ],
    payments: [
      { id: 'p_1', amount_minor: 1_240_000, currency: 'MYR', method: 'Bank transfer', recorded_at: '2026-04-26T08:14:00Z', reference: 'PT-2604-A' },
    ],
    terms_and_conditions: 'Net 30 from acceptance.',
    remarks:              null,
    internal_remarks:     null,
    recurrence:           null,
    from_quotation:       { id: 'qt_036', ref: 'QT-036' },
    share_url:            'https://scount.my/i/abc-482',
  },
  {
    id:           'inv_483',
    ref:          'INV-483',
    status:       'draft',
    issue_date:   '2026-04-26',
    due_date:     '2026-05-26',
    contact_name: 'Acme Sdn Bhd',
    contact:      { id: 'c_acme', name: 'Acme Sdn Bhd', email: 'finance@acme.example' },
    delivery_days:        30,
    currency:             'MYR',
    subtotal_minor:       320_754,
    tax_minor:            19_246,
    total_minor:          340_000,
    paid_minor:           0,
    line_items: [
      { description: 'Discovery workshop', quantity: 1, unit_price_minor: 320_754, tax_code: 'SST6', line_total_minor: 340_000 },
    ],
    payments:             [],
    terms_and_conditions: 'Net 30.',
    remarks:              null,
    internal_remarks:     null,
    recurrence:           null,
    from_quotation:       null,
    share_url:            'https://scount.my/i/abc-483',
  },
];
