import type { Contact } from '@/types/api';

export const MOCK_CONTACTS: Contact[] = [
  {
    id:           'c_anugerah',
    type:         'client',
    name:         'PT Anugerah Sdn Bhd',
    email:        'billing@anugerah.example',
    phone:        '+60 12 345 6789',
    tax_id:       'SSM-202101-12345',
    address_line1:'Lot 5, Jalan Kuching',
    address_city: 'Kuching',
    outstanding_minor: 1_240_000,
    invoice_count:     3,
    quote_count:       1,
    currency:          'MYR',
    notes:             'Quarterly retainer client.',
  },
  {
    id:           'c_borneo',
    type:         'client',
    name:         'Borneo Coffee Co.',
    email:        'finance@borneo.example',
    phone:        '+60 82 233 4455',
    tax_id:       null,
    address_line1:'8 Jalan Padungan',
    address_city: 'Kuching',
    outstanding_minor: 620_000,
    invoice_count:     2,
    quote_count:       1,
    currency:          'MYR',
    notes:             null,
  },
  {
    id:           'c_city',
    type:         'client',
    name:         'CityWorks Sdn Bhd',
    email:        'accounts@cityworks.example',
    phone:        '+60 03 7788 9900',
    tax_id:       null,
    address_line1:null,
    address_city: null,
    outstanding_minor: 0,
    invoice_count:     0,
    quote_count:       2,
    currency:          'MYR',
    notes:             null,
  },
  {
    id:           'c_acme',
    type:         'client',
    name:         'Acme Sdn Bhd',
    email:        'finance@acme.example',
    phone:        null,
    tax_id:       null,
    address_line1:null,
    address_city: null,
    outstanding_minor: 0,
    invoice_count:     1,
    quote_count:       0,
    currency:          'MYR',
    notes:             'All paid up.',
  },
  {
    id:           's_tomei',
    type:         'supplier',
    name:         'Tomei Hardware',
    email:        'sales@tomei.example',
    phone:        '+60 03 2222 3333',
    tax_id:       null,
    address_line1:null,
    address_city: 'Petaling Jaya',
    outstanding_minor: 0,
    invoice_count:     0,
    quote_count:       0,
    currency:          'MYR',
    notes:             null,
  },
  {
    id:           's_pos_partners',
    type:         'supplier',
    name:         'POS Partners',
    email:        'ar@pospartners.example',
    phone:        null,
    tax_id:       null,
    address_line1:null,
    address_city: null,
    outstanding_minor: 0,
    invoice_count:     0,
    quote_count:       0,
    currency:          'MYR',
    notes:             null,
  },
];
