import type { Expense } from '@/types/api';
import { MOCK_CASH_ACCOUNTS } from './mock-cash-accounts';
import { MOCK_EXPENSE_CATEGORIES } from './mock-categories';

export const MOCK_EXPENSES: Expense[] = [
  {
    id:             'exp_201',
    ref:            'EXP-201',
    date:           '2026-04-26',
    amount_minor:   18_000,
    tax_minor:      1_080,
    total_minor:    19_080,
    currency:       'MYR',
    category:       MOCK_EXPENSE_CATEGORIES[4],
    paid_from:      MOCK_CASH_ACCOUNTS[1],
    payment_option: 'card',
    contact:        null,
    description:    'Linear monthly · Standard plan',
    internal_remark:null,
    reconciled:     false,
    share_url:      'https://scount.my/e/abc-201',
  },
  {
    id:             'exp_202',
    ref:            'EXP-202',
    date:           '2026-04-24',
    amount_minor:   42_500,
    tax_minor:      2_550,
    total_minor:    45_050,
    currency:       'MYR',
    category:       MOCK_EXPENSE_CATEGORIES[2],
    paid_from:      MOCK_CASH_ACCOUNTS[0],
    payment_option: 'cash',
    contact:        null,
    description:    'Client lunch · CityWorks',
    internal_remark:'Billable to project',
    reconciled:     true,
    share_url:      'https://scount.my/e/abc-202',
  },
  {
    id:             'exp_203',
    ref:            'EXP-203',
    date:           '2026-04-22',
    amount_minor:   12_000,
    tax_minor:      0,
    total_minor:    12_000,
    currency:       'MYR',
    category:       MOCK_EXPENSE_CATEGORIES[1],
    paid_from:      MOCK_CASH_ACCOUNTS[1],
    payment_option: 'card',
    contact:        null,
    description:    'Grab to client site',
    internal_remark:null,
    reconciled:     false,
    share_url:      'https://scount.my/e/abc-203',
  },
  {
    id:             'exp_204',
    ref:            'EXP-204',
    date:           '2026-04-20',
    amount_minor:   320_000,
    tax_minor:      19_200,
    total_minor:    339_200,
    currency:       'MYR',
    category:       MOCK_EXPENSE_CATEGORIES[5],
    paid_from:      MOCK_CASH_ACCOUNTS[1],
    payment_option: 'bank',
    contact:        { id: 's_tomei', name: 'Tomei Hardware', email: 'sales@tomei.example' },
    description:    'Q1 server hosting',
    internal_remark:null,
    reconciled:     true,
    share_url:      'https://scount.my/e/abc-204',
  },
  {
    id:             'exp_205',
    ref:            'EXP-205',
    date:           '2026-04-15',
    amount_minor:   45_000,
    tax_minor:      2_700,
    total_minor:    47_700,
    currency:       'MYR',
    category:       MOCK_EXPENSE_CATEGORIES[6],
    paid_from:      MOCK_CASH_ACCOUNTS[2],
    payment_option: 'online',
    contact:        null,
    description:    'Meta Ads · April campaign',
    internal_remark:null,
    reconciled:     false,
    share_url:      'https://scount.my/e/abc-205',
  },
];
